import Animation from "./animation";
import Link from 'next/link';

export default function Hero() {
    return (
        <>
            <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
                <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">I'm Hugo, everybody is doing well.
                </h1>
                <p className="mb-8 leading-relaxed">It is also called eddy current, eddy current, or eddy current, and in honor of the first discovered one, it is also called Foucault current. It is a vortex-type current generated by electromagnetic induction when the magnetic field around a conductor changes rapidly.<br /><br />
                    P=(tfB) ^2 [W] <br />
                    t is the thickness of the conductor, f is the frequency [Hz], and B is the magnetic flux density [Wb/m^2] <br /><br />

                    When eddy current is generated, heat is generated in the iron core, resulting in loss, which is called eddy current loss. It is a loss that occurs in various transformers or inductors and is classified as an iron loss along with hysteresis loss.</p>
                <div className="flex justify-center">
                    <Link href='/projects'>
                        <button className="btn-project">프로젝트 보러가기</button>
                    </Link>


                </div>
            </div>
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
                <Animation />
            </div>
        </>
    )
}